// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3550.Robotronix2017.subsystems;


import org.usfirst.frc3550.Robotronix2017.RobotMap;
import org.usfirst.frc3550.Robotronix2017.commands.*;
import com.ctre.CANTalon;

import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.TalonSRX;
import edu.wpi.first.wpilibj.VictorSP;
//import edu.wpi.first.wpilibj.TalonSRX;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class RamasseurSubsystem extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final VictorSP motorRamasseurArriere = RobotMap.ramasseurMoteurArriere; //Droit
    private final VictorSP motorRamasseurAvant = RobotMap.ramasseurMoteurAvant; //Gauche
    private final DoubleSolenoid pistonPushDroit = RobotMap.pistonPushDroit;
    private final DoubleSolenoid pistonPushGauche = RobotMap.pistonPushGauche;
    private final DoubleSolenoid pistonLiftDroit = RobotMap.pistonLiftDroit;
    private final DoubleSolenoid pistonLiftGauche = RobotMap.pistonLiftGauche;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.
   
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
         setDefaultCommand(new ramasseurRepos());
    }
    
    public void Stop(){
    	motorRamasseurArriere.set(0);
    	motorRamasseurAvant.set(0);
    	
  
    }
    public void Ramasser(){
    	motorRamasseurArriere.set(-0.5);
    	motorRamasseurAvant.set(-0.5);
    
    }  
    
    public void Eject(){
    	motorRamasseurArriere.set(0.5);
    	motorRamasseurAvant.set(0.5);
    
    
    
    
   }
    public void Extract(){
    	pistonPushDroit.set(DoubleSolenoid.Value.kForward);  //probablement changer dans false
    	pistonPushGauche.set(DoubleSolenoid.Value.kForward);
   }
    public void Retract(){
    	pistonPushDroit.set(DoubleSolenoid.Value.kReverse); 
    	pistonPushGauche.set(DoubleSolenoid.Value.kReverse);
   }
    public void Up(){
    	pistonLiftDroit.set(DoubleSolenoid.Value.kForward);
    	pistonLiftGauche.set(DoubleSolenoid.Value.kForward);
   } 	
    public void Down(){
    	pistonLiftDroit.set(DoubleSolenoid.Value.kReverse);
    	pistonLiftGauche.set(DoubleSolenoid.Value.kReverse);
   }
    
   public void disablePneumatic(){
	pistonPushDroit.set(DoubleSolenoid.Value.kOff);  //probablement changer dans false
   	pistonPushGauche.set(DoubleSolenoid.Value.kOff);
   	pistonLiftDroit.set(DoubleSolenoid.Value.kOff);
	pistonLiftGauche.set(DoubleSolenoid.Value.kOff);
	   
   }
}
   